from __future__ import annotations

import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"


def run_script(name: str, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(SCRIPTS / name), *args],
        cwd=str(ROOT),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        encoding="utf-8",
    )


class StrictSubmissionGateTests(unittest.TestCase):
    def test_simulation_only_experiments_section_blocks_under_major_threshold(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            draft = Path(tmp) / "paper.tex"
            draft.write_text(
                r"""
\section{Experiments}
We evaluated the method in a 960-run simulation suite.
""",
                encoding="utf-8",
            )
            result = run_script(
                "audit_experiment_boundary.py",
                str(draft),
                "--evidence-boundary",
                "simulation_only",
                "--field",
                "control",
                "--fail-on",
                "major",
            )
            self.assertEqual(result.returncode, 1, result.stdout)
            self.assertIn("experiments_section_for_simulation_only", result.stdout)

    def test_artifact_hygiene_blocks_main_text_script_and_csv_names(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            draft = Path(tmp) / "paper.tex"
            draft.write_text(
                r"""
\section{Simulation Study}
The results were generated by switching_topology_experiments/run_eval.py and aggregate.csv.
""",
                encoding="utf-8",
            )
            result = run_script("audit_artifact_hygiene.py", str(draft))
            self.assertEqual(result.returncode, 1, result.stdout)
            self.assertIn("main_text_artifact_path", result.stdout)

    def test_contribution_structure_flags_evaluation_only_and_too_many_bullets(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            draft = Path(tmp) / "paper.md"
            draft.write_text(
                """
## Contributions
- We introduce the formulation.
- We design the allocator lifecycle.
- We add the repair transaction.
- We analyze the certificate.
- We report simulations and provide code.
""",
                encoding="utf-8",
            )
            result = run_script("audit_contribution_structure.py", str(draft), "--fail-on", "major")
            self.assertEqual(result.returncode, 1, result.stdout)
            self.assertIn("too_many_contribution_bullets", result.stdout)
            self.assertIn("evaluation_only_contribution", result.stdout)

    def test_simulation_reporting_flags_repeated_table_diagnostic(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            draft = Path(tmp) / "paper.tex"
            draft.write_text(
                r"""
\begin{tabular}{lcc}
A & method1 & 4.803\times 10^{-3}\\
A & method2 & 4.803\times 10^{-3}\\
B & method1 & 4.803\times 10^{-3}\\
B & method2 & 4.803\times 10^{-3}\\
\end{tabular}
""",
                encoding="utf-8",
            )
            result = run_script("audit_simulation_reporting.py", str(draft), "--fail-on", "major")
            self.assertEqual(result.returncode, 1, result.stdout)
            self.assertIn("repeated_table_diagnostic_value", result.stdout)

    def test_reference_maturity_flags_arxiv_dominated_bibliography(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            bib = Path(tmp) / "refs.bib"
            bib.write_text(
                r"""
@article{a,
  title={A},
  author={Author, A.},
  year={2024},
  eprint={2401.00001},
  archivePrefix={arXiv}
}
@article{b,
  title={B},
  author={Author, B.},
  year={2023},
  eprint={2301.00001},
  archivePrefix={arXiv}
}
""",
                encoding="utf-8",
            )
            result = run_script("audit_reference_maturity.py", str(bib), "--fail-on", "major")
            self.assertEqual(result.returncode, 1, result.stdout)
            self.assertIn("high_arxiv_reference_ratio", result.stdout)

    def test_runner_blocks_publication_polish_for_missing_strict_inputs(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            project = Path(tmp)
            (project / "paper.tex").write_text(
                r"""
\title{A Novel Controller}
\begin{abstract}
We guarantee distributed connectivity preservation from a simulation-only study.
\end{abstract}
\section{Experiments}
We evaluated the method in simulation.
\section{Conclusion}
The method guarantees robust real-world deployment.
""",
                encoding="utf-8",
            )
            result = run_script(
                "run_ieee_submission_gates.py",
                str(project),
                "--evidence-boundary",
                "simulation_only",
                "--fail-on",
                "major",
            )
            self.assertEqual(result.returncode, 1, result.stdout)
            self.assertIn("Strict Submission Gate Summary", result.stdout)
            self.assertIn("BLOCKED", result.stdout)


if __name__ == "__main__":
    unittest.main()
